[[main]]
identifier = "home"
name = "首页"
url = "/zh-cn/"
weight = 1

[main.params]
icon = "home"
newtab = false

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/junevision"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/jun-lei-90755591/"

[social.params]
icon = "linkedin"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/junevision/"

[social.params]
icon = "instagram"